### PR TITLE
Wording changes

### PR DESCRIPTION
**Pull request by Buzzardo**
Replacing some terms

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
@marcingrzejszczak do we even need this file checked in any longer?  I thought you said with the latest docs changes we didnt need it?  Maybe we need to keep it around for older branches?

**Comment by marcingrzejszczak** [comment]
Nope, the file can be deleted.

**Comment by Buzzardo** [comment]
Many of the spring-cloud-* projects have a ghpages.sh file. Can we remove all of them?

**Comment by marcingrzejszczak** [comment]
Yes, let's leave only the one in spring-cloud-build.

**Pull request merged**
