### PR TITLE
Cleanup disabling of zookeeper config

### PR DESCRIPTION
**Pull request by Cs4r**
Unit test + code needed to fix the bug described in #124

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Cs4r Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-zookeeper&pullRequestId=125)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-zookeeper&pullRequestId=125) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Cs4r Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-zookeeper&pullRequestId=125)!

**Comment by Cs4r** [comment]
You are totally right. I have just addressed your comment (and undone previous changes).

Shall we create an annotation similar to @ConditionalOnZookeeperEnabled for this particular action? Something like @ConditionalOnZookeeperConfigEnabled ?

i.e: 

```
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
@ConditionalOnProperty(value = "spring.cloud.zookeeper.config.enabled", matchIfMissing = true)
public @interface ConditionalOnZookeeperConfigEnabled {
}
```

BTW, @spencergibb any suggestions about how to test this bugfix?

**Comment by Cs4r** [comment]
Added tests. Let me know if they need to be improved (in case they do, provide me some hints)

**Pull request merged**
