### PR TITLE
Generate correct path for different slash variations

### PR DESCRIPTION
**Pull request by dstepanov**

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
@dstepanov you've mentioned that this PR is not yet ready due to some issues with the root entry? Should we close it for now?

**Comment by dstepanov** [comment]
I have come up with a different solution to sanitize dependency path, prefix and root in the initialization, unfortunately it changes some default behavior, please check:

https://github.com/spring-cloud/spring-cloud-zookeeper/compare/master...dstepanov:fix-slash-v2?expand=1

**Comment by dstepanov** [comment]
WDYT @marcingrzejszczak @spencergibb?

**Comment by dstepanov** [comment]
Will provide a new PR with presented solution

**Pull request closed without merging**
